#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRental
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AutoRental")]
	public partial class AutoTypesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAutoType(AutoType instance);
    partial void UpdateAutoType(AutoType instance);
    partial void DeleteAutoType(AutoType instance);
    #endregion
		
		public AutoTypesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoTypesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoTypesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoTypesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AutoType> AutoTypes
		{
			get
			{
				return this.GetTable<AutoType>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AutoTypes")]
	public partial class AutoType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AutoTypeID;
		
		private string _AutoType1;
		
		private int _Capacity;
		
		private decimal _DailyRate;
		
		private decimal _WeeklyRate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAutoTypeIDChanging(int value);
    partial void OnAutoTypeIDChanged();
    partial void OnAutoType1Changing(string value);
    partial void OnAutoType1Changed();
    partial void OnCapacityChanging(int value);
    partial void OnCapacityChanged();
    partial void OnDailyRateChanging(decimal value);
    partial void OnDailyRateChanged();
    partial void OnWeeklyRateChanging(decimal value);
    partial void OnWeeklyRateChanged();
    #endregion
		
		public AutoType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AutoTypeID
		{
			get
			{
				return this._AutoTypeID;
			}
			set
			{
				if ((this._AutoTypeID != value))
				{
					this.OnAutoTypeIDChanging(value);
					this.SendPropertyChanging();
					this._AutoTypeID = value;
					this.SendPropertyChanged("AutoTypeID");
					this.OnAutoTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AutoType", Storage="_AutoType1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AutoType1
		{
			get
			{
				return this._AutoType1;
			}
			set
			{
				if ((this._AutoType1 != value))
				{
					this.OnAutoType1Changing(value);
					this.SendPropertyChanging();
					this._AutoType1 = value;
					this.SendPropertyChanged("AutoType1");
					this.OnAutoType1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Int NOT NULL")]
		public int Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this.OnCapacityChanging(value);
					this.SendPropertyChanging();
					this._Capacity = value;
					this.SendPropertyChanged("Capacity");
					this.OnCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DailyRate", DbType="Money NOT NULL")]
		public decimal DailyRate
		{
			get
			{
				return this._DailyRate;
			}
			set
			{
				if ((this._DailyRate != value))
				{
					this.OnDailyRateChanging(value);
					this.SendPropertyChanging();
					this._DailyRate = value;
					this.SendPropertyChanged("DailyRate");
					this.OnDailyRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeeklyRate", DbType="Money NOT NULL")]
		public decimal WeeklyRate
		{
			get
			{
				return this._WeeklyRate;
			}
			set
			{
				if ((this._WeeklyRate != value))
				{
					this.OnWeeklyRateChanging(value);
					this.SendPropertyChanging();
					this._WeeklyRate = value;
					this.SendPropertyChanged("WeeklyRate");
					this.OnWeeklyRateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
